### ISSUE TITLE
Installing using pip3 requires protobuf to be installed

### ISSUE THREAD

**Issue by janmayer** [cartoonist/pystream-protobuf#6]
On a fresh install of python 3.5.2 with pip 8.1.2 (using pyenv), installing pystream-protobuf fails if protobuf has not been installed first:

```
$ pip3 install pystream-protobuf
Collecting pystream-protobuf
  Using cached pystream-protobuf-1.2.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-gu76whjp/pystream-protobuf/setup.py", line 10, in <module>
        import stream
      File "/tmp/pip-build-gu76whjp/pystream-protobuf/stream/__init__.py", line 28, in <module>
        from .stream import open    # noqa pylint: disable=redefined-builtin
      File "/tmp/pip-build-gu76whjp/pystream-protobuf/stream/stream.py", line 34, in <module>
        from google.protobuf.internal.decoder import _DecodeVarint as varintDecoder
    ImportError: No module named 'google'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-gu76whjp/pystream-protobuf/

$ pip3 install protobuf
...
Installing collected packages: six, protobuf
Successfully installed protobuf-3.1.0.post1 six-1.10.0

$ pip3 install pystream-protobuf
...
Installing collected packages: protobuf, pystream-protobuf
  Found existing installation: protobuf 3.1.0.post1
    Uninstalling protobuf-3.1.0.post1:
      Successfully uninstalled protobuf-3.1.0.post1
  Running setup.py install for pystream-protobuf ... done
Successfully installed protobuf-3.0.0 pystream-protobuf-1.2.2
```

**Comment by cartoonist** [comment]
Thanks for reporting this issue. I will fix it soon.
